### ISSUE TITLE
Protocol json structure

### ISSUE THREAD

**Issue by GrimTheReaper** [PrismarineJS/minecraft-data#235]
I have a few questions about the protocol json structure.
1) Why are the packets in an object and not an array?
2) Packets are structures like the following:
``` json
"packet_example": [
  "container",
  [
    {
      "name": "protocolField",
      "type": "varint"
    }
  ]
]
```
2) Why are these packets arrays (and not even typed arrays) and not types? This lib is supposed to be language agnostic yet it uses types that aren't friendly to strict typed languages.
3) wiki.vg says JSON is a type. While I get that JSON objects are just strings, shouldn't they have their own type?

**Comment by rom1504** [comment]
This is the description of the format of protocol.json https://github.com/ProtoDef-io/ProtoDef

1. An object is defining types key is name value is type definition

2. There is no packet, only types. Which array are you talking about ? You are free to use whatever type your language offer.

3. Because they are string. Yes we may add type alias in protodef but didn't do it yet, I think there's an open issue for that

**Comment by GrimTheReaper** [comment]
Thank you, that adds quite a bit of clarity, and ProtoDef should help me.

I'll pass by the first question because my issue is kinda resolved. 

I guess my main issue is with [structure](https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes.md#structures). I think its weird that the type (ie container, array, count), is stored as an array of just data like:
``` json
[
  "container",
  [
    {
      "name": "protocolField",
      "type": "varint"
    }
  ]
]
```

Instead of something like...
``` JSON
[
  {
    "type": "container",
    "data": [
      {
        "name": "protocolField",
        "type": "varint"
      }
    ]
  }
]
```

This can be seen [here](https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.10/protocol.json), a good example is `status.toClient.types.packet_server_info`
I don't fully get why you didn't just type these structures, and instead chose to make its type an array of any (oneof string, array, object it seems).

As for the JSON type alias I don't really see it as a blocker or detrimental. I just feel like it might lead to a better understanding of how the data of the packet is actually being used.

**Comment by roblabla** [comment]
Protodef actually used to support `{ "type": "typename", "args": /* arguments here */ }` eons ago. It was removed because it's noisy and not helpful. The array-format is easier to read. Everything follows `["type", arguments]` where `arguments`' type depends on the type.

**Comment by GrimTheReaper** [comment]
@roblabla just out of curiosity, how do you handle/reference that then in your language of choice?

Also, what do you mean by noisy and not helpful? Its databinding. If anything happens to the position of the array, you still have the `type` bound to the `argument`.

Anyway, for reference, this is how I imagine it'd be dealt with in java. I don't see how this is any cleaner 

Without types
``` java
for (int i = 0; i < objects.length; i+=2) {
  if (objects[i] instanceof String && ((String)objects[i]) == "type") {
    ((TypeClass)objects[i+1]) ....
  }
}
```
With Types
Where as if you had the actual types..
``` java
for (int i = 0; i < objects.length; i++ {
  if (objects[i].type == "type") {
    ((TypeClass)objects[i].data) ...
  }
}
```

**Comment by rom1504** [comment]
"container" is the equivalent to a struct. It is fully typed.
"data" or not is a question of json syntax which doesn't change anything but readability

For alias I never said it was a blocker, just that it's a task that hasn't been done yet .

Please read protodef doc ;)

You may also be interested by protodefc, it's in the same org, have a look ;)

**Comment by GrimTheReaper** [comment]
@rom1504

No, "container" is not the equivalent to a struct, because you can't do native mapping with it. You can't just decode/unmarshal it to a Java class (or a struct in Golang) without jumping through hoops. 

I know you said that JSON alias wasn't a blocker. *I was clarifying that I didn't mean to make it seem like it was*

I've read protodef as well as protodefc. And I don't know why you even bother with this type, especially when you have to add a [custom reader just for container](https://github.com/ProtoDef-io/protodefc/blob/master/src/frontend/protocol_json/variants/container.rs) instead of dealing with the fields themselves. 

My main point, *why* are you using this weird pesudo type? You say that it's more helpful, but I've sent this JSON blob around both my team and my office and not a single one of our developers gets it. Also, I don't really care if you change. I've already moved to use burger. I'm just curious as to why you guys are the way that you are.

**Comment by roblabla** [comment]
> No, "container" is not the equivalent to a struct

`container` is absolutely the equivalent to a struct. You could absolutely turn it into a C struct, and (ignoring alignment), cast a `char*` to that struct. I had a prototype protodef compiler targetting C that worked this way for zero-overhead deserialization.

>  a custom reader just for container instead of dealing with the fields themselves.

I don't even understand what you mean here? In node-protodef (the original protodef implementation), everything had to be read with a custom reader: https://github.com/ProtoDef-io/node-protodef/tree/master/src/datatypes. I must admit I'm not super familiar with the workings of protodefc.

Container is just a type that represents a container of sequential, named fields. It's a product type. We also have union/sum types in the form of `mapper`. A `mapper` associates a discriminant value with an underlying type. It doesn't directly contain the fields because that is not its responsibility.

There are many protocols where the top-level is not a mapper, but a container. In fact, minecraft is an example, since a packet is basically

```json
["container", [
    { "name": "length", "type": "u32" },
    { "name": "data", "type": "packet" }
]]
```

(We don't actually deserialize the length in protodef directly though, so you won't see this anywhere).

The container type is extremely important, and cannot be replaced. Here are some more example usages:

- An array of structure is an `["array", { "type": ["container", []]`. Giving array the fields directly would not make sense, since it could be an array of primitive types.
- An optional structure is `["option", ["container", []]`. Again, it wouldn't make sense to directly put the fields in the option (like `["option", [ { name: "length", type: "u32" }]]`) because you could have an option of primitive types.

So I hope that I answered this question:

> why are you using this weird pesudo type?

As for the readability claim, this is totally independent of what container is. In protodef, we have types. The built-in ones include simple ones like `u32`, `varint`,`bool` or `void` don't take any argument. As such, they are represented in the json directly as a string. `"u32"` is a type.

Then we have more complicated types, like `bitfield`, which takes an argument describing the layout of the bitfield. Those are denoted as an array, the first element is the type name, and the second element is the type's argument. e.g.:

```json
["bitfield", [
      { "name": "x", "size": 26, "signed": true },
      { "name": "y", "size": 12, "signed": true },
      { "name": "z", "size": 26, "signed": true }
    ]]
```

Additionally, we have types that themselves take other types as arguments, generally containers. Those include `container`, `array`, `switch`, `mapper`, and many other types.

As we previously said, a type is either the bare `"typename"` if the type takes no argument, or `["typename", arguments]` if it takes arguments. So we can have this:

```json
["container", [
    { "name": "x", "type": "i32" },
    { "name": "y", "type": "i32" },
    { "name": "z", "type": "i32" }
]]
```

Which is a equivalent to

```c
struct {
    int x;
    int y;
    int z;
}
```

We could also have more complicated types, such as:

```json
["container", [
    { "name": "name", "type": "string" },
    { "name": "arr", "type": ["array", {
        "countType": "varint",
        "type": ["container", [
            { "name": "x", "type": "u32" },
            { "name": "y", "type": "u32" },
            { "name": "z", "type": "u32" },
        ]]
    }]}
]]
```

Which is equivalent to the following C structure (comments indicate things that are not directly representable):

```c
struct {
    char *name;
    int count; // varint
    struct {
        int x;
        int y;
        int z;
    } arr[]; // Size of array is count
};
```

As you can see, we can deeply nest the types (including `container`) inside other types to create complex structures, which allow us to represent almost any possible data encoding in a declarative way.

If we used the `{ "name", "type" }` format, those deeply nested structures would be extremely painful to read. I don't take much sympathy to the `[1][0]` argument. Sure, this could be rewritten `.args.type`, but it's not really a big problem, and the readability gain in protodef files, at least IMO, outweight the loss of readability in the data definition.

Two last points: `protodefc` actually support a separate format, called the `pds`. It's possible to transform a json to a pds and a pds to a json with protodefc, but the `pds` files are, again, a lot easier to read: https://github.com/ProtoDef-io/protodefc/blob/master/test.pds. If you're having trouble understanding the JSON files, it might be worth using protodefc to turn it into a pds.

Finally, while it's not generic for all protodef files (unfortunately), we do have a very complete documentation tool for the minecraft files: http://minecraft-data.prismarine.js.org/?d=protocol. It might help you figure out how it works.

**Comment by rom1504** [comment]
Thanks for the detailed explanation @roblabla
@GrimTheReaper you will soon figure out it's impossible to generate a full parser from the protocol data that burger currently extract, but good luck

**Comment by GrimTheReaper** [comment]
@rom1504 Thank you.
@roblabla Thank you for your explanation, although I think that you should rethink readability of your `pds` vs parsability of your `json`.
