### ISSUE TITLE
How to parse protocol

### ISSUE THREAD

**Issue by HurricanKai** [PrismarineJS/minecraft-data#393]
I've been trying to parse the protocol.json files for two weeks now, and I can't get it to work for all the types. I can get some good approaches, but then I fail to parse things like particleDatas `"compareTo": "$compareTo",` or `compareTo`s with `..`
What's the intended way to parse the protocol files? There has to be some model they are produced from, how is that structured?
(I'm super confused about why the types are represented with arrays in the first place, shouldn't that be an object normally?)

**Comment by rom1504** [comment]
hi,
the format is https://github.com/ProtoDef-io/ProtoDef

**Comment by HurricanKai** [comment]
Hi, thanks! That seems like it's going to be very helpful. In terms of code, what I can see at a glance is that the "base" format is
`[ "type_name", { options } ]` I guess what threw me off is that `options` is very very generic.
I'll try again with this though :) thanks a lot.

**Comment by HurricanKai** [comment]
Bit of a follow-up question, and I didn't want to make yet another issue.
switch is documented in https://github.com/ProtoDef-io/ProtoDef/blob/master/doc/datatypes/conditional.md
and compareTo is documented as
> compareTo : the value is the other field
what exactly is allowed there? I've seen constructs which use `$something` were they are then re-used somewhere else, providing `something` in the options.
I've also seen constructs with `..`, so I'm wondering what I should support here.

**Comment by ForeverZer0** [comment]
@rom1504 The problem is that ProtoDef is not documented properly. While the link you provided answers the headline of the question in the general sense, it fails to address the root problem and the specific description of it, which is related to the nebulous "variable system" that is not documented anywhere in the ProtoDef spec. While I understand this isn't the proper place to discuss it, the [same issue](https://github.com/ProtoDef-io/ProtoDef/issues/20) has been open for nearly 6 years without being addressed, so it doesn't appear to be a focus there.

This is project is pretty much the reference implementation for ProtoDef, and practically-speaking, more useful than its actual sparse and very lacking documentation, Both projects would benefit greatly from a few additions to the ProtoDef docs, and save the headache of digging through schemas and trying to discern whats going on in a large example file, and how it should be properly handled. This is especially important for statically typed languages and parsers only capable of forward-reading (i.e. "particleData" is referenced in "particle", but defined after it).

**Comment by rom1504** [comment]
https://github.com/ProtoDef-io/ProtoDef/issues/20 yes would be great to document the variable system

Are you interested in helping out?

**Comment by ForeverZer0** [comment]
I would be happy to clarify and expand the ProtoDef wiki, it was actually already on my todo list once I get it figured out completely (I am creating a C# implementation of it). Though I still need to understand how the variables work myself before I attempt to document it. I have been searching around both projects and checking issues for clarification, but nothing answers it.

Even a general explanation on the "rules" regarding them would be helpful to figuring it out. As it stands, it is basically "this is what to expect, except sometimes there is just a word with a $ prefix" with no explicit explanation on what it means. I can make some educated guessed and surmise how it works. That might work well enough when using a fixed example (i.e. minecraft-data) if I just want to get it to work, but that is not helpful for implementing a specification with unknowns. I had assumed that, while closely linked, ProtoDef was a separate entity from this one, and could have other uses outside of it, hence my reluctance to just base it off what I see in minecraft-data.

**Comment by rom1504** [comment]
Here is the reference implementation
https://github.com/ProtoDef-io/node-protodef/blob/master/src/protodef.js#L25

Documentation / the general spec should follow that.
