### ISSUE TITLE
fix protocol update bot

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#707]
https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/protocolVersions.json is not up to date

even though https://github.com/PrismarineJS/minecraft-data/commit/68a73b58f54cf59e968f0f0f4c92ac63f317f7d6

what could be wrong @extremeheat ?

**Comment by extremeheat** [comment]
It checks the versions.json to see if it's there first before adding to protocolVersions.json
https://github.com/PrismarineJS/minecraft-data/blob/7ec47f149df4a9cd42a98f7551aa95dbc9028836/.github/helper-bot/index.js#L60

So since the other PR that added data added to versions.json (but not protocolVersions.json) it didn't do anything

https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/common/versions.json

Should we ignore the versions.json and just check the protocolVersions.json ? Shouldn't be a problem for next release

**Comment by rom1504** [comment]
protocolVersions.json should contain all versions whereas versions.json is only supported versions
