### ISSUE TITLE
Several 1.20.2 recipes have invalid shape data (PC)

### ISSUE THREAD

**Issue by qpn6ph9q** [PrismarineJS/minecraft-data#804]
Several recipes in https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.20.2/recipes.json have invalid shape data.

For example: The shape data for iron_door (688) has the orientation flipped in the 1.20.2 data:

```
  "688": [
	{
	  "inShape": [
		[
		  770,
		  770,
		  770
		],
		[
		  770,
		  770,
		  770
		]
	  ],
	  "result": {
		"id": 688,
		"count": 3
	  }
	}
  ]
```
The shape data is correct in the [1.20.0/1.20.1](https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.20/recipes.json) data:

```
  "688": [
	{
	  "inShape": [
		[
		  770,
		  770
		],
		[
		  770,
		  770
		],
		[
		  770,
		  770
		]
	  ],
	  "result": {
		"count": 3,
		"id": 688
	  }
	}
  ]
```

**Comment by wgaylord** [comment]
Interesting, looks like https://github.com/PrismarineJS/minecraft-data-generator-server does not output the recipes in the same shape that what ever tool was used for 1.20.1 does.  Not sure how the tests didn't catch this. I guess because its still valid technically.  I will see if I can fix that tool then, since it worked so well for everything else.

**Comment by wgaylord** [comment]
Okay, I will be making a PR with the 1.20.2 data fixed and also adding a test to check that the iron door is not rotated. (Since that is a simple way to catch this.)
