### ISSUE TITLE
Supporting several protocol versions

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/minecraft-data#9]
The current plan is to support minecraft 1.8.
But at some point 1.9 will be out, and supporting both version might be nice.
How could we support multiple versions ?
Different branches ? Different folders ?

(this is a long-term issue, mainly becoming relevant when 1.9 comes out)

**Comment by rom1504** [comment]
I think different branches would probably be the best, so we can backport thing more easily.

**Comment by deathcap** [comment]
How would different branches work on NPM, would there be separate modules minecraft-data-1.8, minecraft-data-1.7, etc., or different major versions of https://www.npmjs.com/package/minecraft-data?

If the latter, this could cause problems with cross-protocol support; since [package.json](https://docs.npmjs.com/files/package.json#dependencies) "dependencies" is keyed by module name so only one minecraft-data module could be listed in each package.json. (Though I suppose this could be worked around in the dependent module by creating separate directories with different package.json's adding each specific minecraft-data module version.)

**Comment by rom1504** [comment]
> creating separate directories with different package.json's adding each specific minecraft-data module version

yeah this would probably be the plan (because a dependent module might want to support multiple version at the same time ( @roblabla would like to do that in node-minecraft-protocol (when he's done Protocols and node-minecraft-protocol is mainly a .json that can be added to minecraft-data)))
So I guess different major versions.

**Comment by rom1504** [comment]
see https://github.com/PrismarineJS/node-minecraft-data/issues/4

**Comment by rom1504** [comment]
What has been done here : 
* a branch for each mc version (currentl 1.8 and 1.9)
* no master branch

Next step is fixing PrismarineJS/node-minecraft-data#4

**Comment by rom1504** [comment]
done
